DROP DATABASE IF EXISTS top_songsDB;
CREATE DATABASE top_songsDB;
USE top_songsDB;

CREATE TABLE top_5000_songs (
id INTEGER(10) NOT NULL PRIMARY KEY,
artist VARCHAR(255),
song VARCHAR(255),
year INTEGER(10),
raw_total FLOAT(13) NULL,
raw_usa FLOAT(13) NULL,
raw_uk FLOAT(13) NULL,
raw_eur FLOAT(13) NULL,
raw_row FLOAT(13) NULL);

CREATE TABLE top_3000_albums (
id INTEGER(10) NOT NULL PRIMARY KEY,
artist VARCHAR(255),
album VARCHAR(255),
year INTEGER(10),
raw_total FLOAT(13) NULL,
raw_usa FLOAT(13) NULL,
raw_uk FLOAT(13) NULL,
raw_eur FLOAT(13) NULL,
raw_row FLOAT(13) NULL);

SELECT * FROM Top5000;